// Code generated by go2go; DO NOT EDIT.


//line print.go2:1
package main

//line print.go2:1
import "fmt"

//line print.go2:11
func main() {
//line print.go2:11
 instantiate୦୦Prn୦string([]string{"hi, ", "i0Ek3\n"})
			instantiate୦୦Prn୦int([]int{1, 2, 3})
//line print.go2:14
}
//line print.go2:5
func instantiate୦୦Prn୦string(s []string,) {
	for _, v := range s {
		fmt.Print(v)
	}
}
//line print.go2:5
func instantiate୦୦Prn୦int(s []int,) {
	for _, v := range s {
		fmt.Print(v)
	}
}

//line print.go2:9
type Importable୦ int

//line print.go2:9
var _ = fmt.Errorf
